<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Mapping;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $repository;
    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->repository = $this->getEntityManager()->getRepository('AppBundle:Category');
    }

    public function getBrands(){
        $brands = $this->repository
            ->findBy([
                'isBrand' => true,
            ]);

        return $brands;
    }

}