<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveOffer(){
        $activeOffers = $this->getEntityManager()->getRepository('offer')
            ->createQueryBuilder('o')
            ->where('o.startDate <= :date AND o.endDate >= :date')
            ->setParameter('date', new \DateTime(), Type::DATE)
            ->getQuery()->getResult();
        return $activeOffers;
    }

}