<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Mapping;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    private $repository;
    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->repository = $this->getEntityManager()->getRepository('AppBundle:Page\Page');
    }

    public function getPage($pageName){

        $page = $this->repository->findOneBy([
                                        'name' => $pageName,
                                    ]);
        return $page;
    }

}