<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Mapping;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    private $repository;
    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->repository = $this->getEntityManager()->getRepository('AppBundle:Blog\Post');
    }

    public function getLastPost($amount = 3){
        $lastPosts = $this->repository
            ->createQueryBuilder('p')
            ->orderBy('p.createdDate', 'DESC')
            ->setMaxResults($amount)->getQuery()->getResult();

        return $lastPosts;
    }

}