<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\Mapping;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    private $repository;
    public function __construct($em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
        $this->repository = $this->getEntityManager()->getRepository('AppBundle:Product');
    }

    public function getRecents($amount = 50){
        $recentProduct = $this->repository
            ->findBy([
            'recent' => true,
        ], null, $amount);

        return $recentProduct;
    }

    public function getInStore($amount = 50){
        $inStore = $this->repository
            ->findBy([
                'inStore' => true,
            ], null, $amount);

        shuffle($inStore);
        $inStore = array_slice($inStore,  0,50);

        return $inStore;
    }

    public function getPopulars($amount = 50){
        $populars = $this->repository
            ->createQueryBuilder('product')
            ->where('product.popular = true')
            ->orderBy('product.priority', 'DESC')
            ->setMaxResults($amount)
            ->getQuery()
            ->getResult();

        return $populars;
    }

}