<?php

namespace AppBundle\Repository;

/**
 * PromotionEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
