ALTER TABLE product ADD is_parent TINYINT(1) DEFAULT NULL;

CREATE TABLE similar_product (id INT AUTO_INCREMENT NOT NULL, parent_product_id INT DEFAULT NULL, product_id INT DEFAULT NULL, INDEX IDX_66C395B92C7E20A (parent_product_id), INDEX IDX_66C395B94584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE similar_product ADD CONSTRAINT FK_66C395B92C7E20A FOREIGN KEY (parent_product_id) REFERENCES product (id);
ALTER TABLE similar_product ADD CONSTRAINT FK_66C395B94584665A FOREIGN KEY (product_id) REFERENCES product (id);

