DROP TABLE IF EXISTS welcome_email_post;
DROP TABLE IF EXISTS welcome_email_product;
DROP TABLE IF EXISTS welcome_email_offer;
DROP TABLE IF EXISTS welcome_email;

CREATE TABLE welcome_email (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL,
primaryPicture VARCHAR(255) NOT NULL, primaryTitle VARCHAR(255) DEFAULT NULL,
introPicture1 VARCHAR(255) DEFAULT NULL, introTitle1 VARCHAR(255) DEFAULT NULL,
introContent1 LONGTEXT DEFAULT NULL, introLink1 VARCHAR(255) DEFAULT NULL,
introPicture2 VARCHAR(255) DEFAULT NULL, introTitle2 VARCHAR(255) DEFAULT NULL,
introContent2 LONGTEXT DEFAULT NULL, introLink2 VARCHAR(255) DEFAULT NULL,
introPicture3 VARCHAR(255) DEFAULT NULL, introTitle3 VARCHAR(255) DEFAULT NULL,
introContent3 LONGTEXT DEFAULT NULL, introLink3 VARCHAR(255) DEFAULT NULL,
offersTitle VARCHAR(255) DEFAULT NULL, linkOffers VARCHAR(255) DEFAULT NULL,
productsTitle VARCHAR(255) DEFAULT NULL, linkProducts VARCHAR(255) DEFAULT NULL,
promotionPicture VARCHAR(255) DEFAULT NULL, promotionTitle VARCHAR(255) DEFAULT NULL,
promotionContent LONGTEXT DEFAULT NULL, promotionLink VARCHAR(255) DEFAULT NULL,
blogTitle VARCHAR(255) DEFAULT NULL, servicesTitle VARCHAR(255) DEFAULT NULL,
linkServices VARCHAR(255) DEFAULT NULL, servicePicture1 VARCHAR(255) DEFAULT NULL,
serviceTitle1 VARCHAR(255) DEFAULT NULL, serviceContent1 LONGTEXT DEFAULT NULL,
serviceLink1 VARCHAR(255) DEFAULT NULL, servicePicture2 VARCHAR(255) DEFAULT NULL,
serviceTitle2 VARCHAR(255) DEFAULT NULL, serviceLink2 VARCHAR(255) DEFAULT NULL,
serviceContent2 LONGTEXT DEFAULT NULL, footerPicture VARCHAR(255) DEFAULT NULL,
footerPictureLink VARCHAR(255) DEFAULT NULL,
PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE welcome_email ADD active TINYINT(1) NOT NULL;

CREATE TABLE welcome_email_offer (welcome_email_id INT NOT NULL, offer_id INT NOT NULL, INDEX IDX_B203EEEE3C3F24B0 (welcome_email_id), INDEX IDX_B203EEEE53C674EE (offer_id), PRIMARY KEY(welcome_email_id, offer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE welcome_email_product (welcome_email_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_661C839B3C3F24B0 (welcome_email_id), INDEX IDX_661C839B4584665A (product_id), PRIMARY KEY(welcome_email_id, product_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE welcome_email_post (welcome_email_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_EB210C4D3C3F24B0 (welcome_email_id), INDEX IDX_EB210C4D4B89032C (post_id), PRIMARY KEY(welcome_email_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE welcome_email_offer ADD CONSTRAINT FK_B203EEEE3C3F24B0 FOREIGN KEY (welcome_email_id) REFERENCES welcome_email (id) ON DELETE CASCADE;
ALTER TABLE welcome_email_offer ADD CONSTRAINT FK_B203EEEE53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) ON DELETE CASCADE;
ALTER TABLE welcome_email_product ADD CONSTRAINT FK_661C839B3C3F24B0 FOREIGN KEY (welcome_email_id) REFERENCES welcome_email (id) ON DELETE CASCADE;
ALTER TABLE welcome_email_product ADD CONSTRAINT FK_661C839B4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE;
ALTER TABLE welcome_email_post ADD CONSTRAINT FK_EB210C4D3C3F24B0 FOREIGN KEY (welcome_email_id) REFERENCES welcome_email (id) ON DELETE CASCADE;
ALTER TABLE welcome_email_post ADD CONSTRAINT FK_EB210C4D4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE;
