ALTER TABLE `category_parent` DROP FOREIGN KEY `FK_3266AA34727ACA70`;
ALTER TABLE `category_parent` ADD CONSTRAINT `FK_3266AA34727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `category_parent` DROP FOREIGN KEY `FK_3266AA34DD62C21B`;
ALTER TABLE `category_parent` ADD CONSTRAINT `FK_3266AA34DD62C21B` FOREIGN KEY (`child_id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `product` DROP FOREIGN KEY `FK_D34A04AD12469DE2`;
ALTER TABLE `product` ADD CONSTRAINT `FK_D34A04AD12469DE2` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE `product_images` DROP FOREIGN KEY `FK_8263FFCE4584665A`;
ALTER TABLE `product_images` ADD CONSTRAINT `FK_8263FFCE4584665A` FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
