easy_admin:
    design:
        menu:
            - { entity: 'Product', label: 'Producto' }
            - { entity: 'Evaluation', label: 'Evaluaciones' }
            - { entity: 'Category', label: 'Categoría' }
            - { entity: 'Phone', label: 'Teléfonos' }
            - { entity: 'Offer', label: 'Ofertas' }
            - { entity: 'Request', label: 'Pedidos'}
            - { entity: 'PreFacture', label: 'Prefacturas'}
            - { entity: 'Facture', label: 'Facturas'}
            - { entity: 'ExternalRequest', label: 'Ordenes de Compra'}
            - { entity: 'Member', label: 'Miembros' }
            - {entity: 'Client', label: 'Clientes'}
            - { label: 'Actualizar App', route: 'upload_app'}
            - { label: 'Configuración General', route: 'config_view' }
            - label: 'Blog'
              children:
                  - { entity: 'Post', label: 'Artículos'}
                  - { entity: 'BlogCategory', label: 'Categorías'}
                  - { entity: 'Tag', label: 'Tags'}
            - { entity: 'Page', label: 'Páginas'}
            - { entity: 'User', label: 'Usuarios'}
            - { entity: 'PromotionEmail', label: 'Correos'}
